Исключения для артефактов в Лиманске
dsh2dsh/op2ogse pull request #21
Opened 2022-10-20 00:10 UTC by ISTORMI

На локе Лиманск осталось множество домов куда невозможно попасть игроку, при этом там бывают артефакты.
Новые места для исключений:
гастроном и подвал
дом, напротив входа в подвал гастронома
дом, слева от входа в дом сталкеров
дом, напротив беседки где 2 мус. бака
2й этаж дома, слева от почтовых ящиков
2й этаж дома, слева от мусорки с тайником

731 ; Крыша дома за локацией -- Поправил, чтоб цепляло аи-сетку за локой.

2022-10-29 13:29 UTC, dsh2dsh requested changes

2022-10-29 13:29 UTC, dsh2dsh commented on gamedata/config/scripts/amk/anoms/anoms.ltx
> +-27.78,  1.41, -180.99, 10 ; ---
Тут можно было сделать одно исключение с большим радиусом, вместо двух?

2022-10-29 14:57 UTC, ISTORMI commented on gamedata/config/scripts/amk/anoms/anoms.ltx
> +-27.78,  1.41, -180.99, 10 ; ---
Прописать координаты исключения в игру можно только в виде куба, если делать по 1-му - будет значительная потеря аи-сетки, соот-но и потеря мест для артов и аномалий. Т.ч. по желанию, можно и 1.

2022-10-29 15:06 UTC, dsh2dsh commented on gamedata/config/scripts/amk/anoms/anoms.ltx
> +-27.78,  1.41, -180.99, 10 ; ---
Почему в виде куба. Здесь указываются сферы. Если одной сферой можно накрыть здание, то так и нужно, вместо того, чтобы указывать две сферы для каждого из этажей, к примеру.

2022-10-29 21:48 UTC, ISTORMI commented on gamedata/config/scripts/amk/anoms/anoms.ltx
> +-27.78,  1.41, -180.99, 10 ; ---
Убрал все кубы и заменил их на сферы, действительно, сферы достаточно одной.

2022-10-30 09:52 UTC, dsh2dsh commented on gamedata/config/scripts/amk/anoms/anoms.ltx
> +-27.78,  1.41, -180.99, 10 ; ---
Как ты вообще эти кубы указывал? Ведь задаются x, y, z и радиус. Как это может быть кубом?

2022-10-30 13:14 UTC, ISTORMI commented on gamedata/config/scripts/amk/anoms/anoms.ltx
> +-27.78,  1.41, -180.99, 10 ; ---
![Снимок222](https://user-images.githubusercontent.com/75955587/198877048-da0d3457-2f90-4b79-9f5f-4ac611fe3e1e.PNG)
Подумав что игра будет ставить куб - это только мой косяк и невнимательность

2022-10-30 15:09 UTC, dsh2dsh approved these changes

2022-10-30 15:10 UTC, merged