Перенос текстовых строк
dsh2dsh/op2ogse pull request #38
Opened 2022-12-30 05:16 UTC by ISTORMI

2022-12-30 14:51 UTC, dsh2dsh requested changes

2022-12-30 14:51 UTC, dsh2dsh commented on gamedata/config/def_localization.ltx
> +encyclopedia
Зачем новый `encyclopedia.xml`, если это можно добавить в один из уже существующих `xml`?

2022-12-30 14:51 UTC, dsh2dsh commented on gamedata/config/def_localization.ltx
> +items
Зачем новый `items` вместо уже существующего `string_table_enc_equipment`?

2022-12-30 14:51 UTC, dsh2dsh commented on gamedata/config/def_localization.ltx
>  string_table_amkzp_arts_desc
Это не относится в переносу строк из скриптов.

2022-12-30 14:51 UTC, dsh2dsh commented on gamedata/config/def_localization.ltx
> -string_table_enc_sigaret
И это тоже.

2022-12-30 14:51 UTC, dsh2dsh commented on gamedata/config/text/rus/string_table_enc_zone.xml
> -		<text>�������� "��������". �������� �������� � ����� ��������� �� ��� ����, ��� ������ ��� ��������, ��� ��������� � ���� ������ �������, ����������� ��� � ������� ����� "���������" � ����� �������
Это и куча всего далее не относится к задаче переноса строк из скриптов.

2022-12-30 14:51 UTC, dsh2dsh commented on gamedata/config/text/rus/encyclopedia.xml
> +		<text>���� �����, ���������� ����������. ��� �������� �������� � ���������� ����� ����� ���������. ��� ����� ������������ ������ �������.</text>
Почему это здесь, в отдельном, новом файле, а не там же, где описаны все остальные части мутантов?

2022-12-30 18:20 UTC, ISTORMI reviewed
Перенос текстовых строк

2022-12-30 18:20 UTC, ISTORMI commented on gamedata/config/def_localization.ltx
> +items
Текст который в новом `items` никак не связан с названием для хмл `string_table_enc_equipment` как и в целом, винегрет который был в данном хмл. Тут иначе совсем никак, кроме как сразу всё на свои места. Если тут что-то откатывать - то это заново нужно делать. Можно разве что не создавать новый `items` а оставить текст в `string_table_enc_equipment` не удаляя его полностью  - а потом, отдельным изменением сделать ренейм для него на `items` ? Как будет лучше?
Все остальные замечания - переделал.

2022-12-31 14:21 UTC, dsh2dsh commented on gamedata/config/def_localization.ltx
> +items
Именно это я и имел ввиду, что незачем создавать новый `items.xml`, если все можно добавить в уже существующий `string_table_enc_equipment.xml`.

2022-12-31 14:23 UTC, dsh2dsh commented on gamedata/config/text/rus/string_table_amk_matras.xml
> -<string_table>
Что изменено в этом файле? Я что-то не обнаруживаю разницы. Если изменения косметические - то они не нужны.

2022-12-31 14:24 UTC, dsh2dsh commented on gamedata/config/text/rus/string_table_amk_metka.xml
> -<string_table>
И здесь тоже.

2022-12-31 14:25 UTC, dsh2dsh commented on gamedata/config/text/rus/string_table_arhara.xml
> -		<text>��� �������� �����. � ���������, ������� ����������, � ��� ������� ������������ ��� ��� ����������. ����� ������ ���� ���� ������ ��������� ���������.</text>
Это и то, что ниже, зачем было удалено? Перенесено в другой файл? Тогда это изменение не нужно. Никаких косметических изменений на данном этапе быть не должно.

2022-12-31 21:07 UTC, ISTORMI commented
Сейчас пр не полный, а для наглядности. Для всех 3-х редактируемых конфигов, уже ранее создан текстовый хмл. В него и нужно всё класть -[gamedata/config/text/rus/devices.xml](https://github.com/dsh2dsh/op2ogse/pull/38/files#diff-e597647b0ac10f1fe252f6e3ce970e5e04562efd28fac7fa60df738ca710ee72) но, эти же конфиги ведут на другие текстовые хмл в которых напихано всё подряд. Из этого, сразу на своё место, одним изменением. Особенно касается файла -[gamedata/config/text/rus/string_table_enc_equipment.xml](https://github.com/dsh2dsh/op2ogse/pull/38/files#diff-9f0c37d48e9da6863302179e351cd2ec3a894c0f936624a7a3ef3ae93533b4d1)

2022-12-31 21:15 UTC, ISTORMI commented on gamedata/config/misc/arhara_items.ltx
>  description			= item_fonarik
Например тут, уже ведет непонятно куда.

2022-12-31 21:19 UTC, ISTORMI commented on gamedata/config/misc/arhara_items.ltx
> -inv_name				= "�������"
А тут у нас просто текст, который нужно переносить, для него и для всех description уже есть ранее созданная хмл [gamedata/config/text/rus/devices.xml](https://github.com/dsh2dsh/op2ogse/pull/38/files#diff-e597647b0ac10f1fe252f6e3ce970e5e04562efd28fac7fa60df738ca710ee72)

2022-12-31 21:25 UTC, ISTORMI commented on gamedata/config/misc/arhara_items.ltx
> -inv_name				= "�������"
`description` как в примере, и весь подобный "разнобой" перемещен сразу на своё место.

2022-12-31 21:29 UTC, ISTORMI commented on gamedata/config/text/rus/devices.xml
> +	<string id="fonarik">
Из примера, теперь и название и описание рядом, в одном, правильном месте. А не в раных разнобой хмл

2023-01-01 15:15 UTC, dsh2dsh requested changes

2023-01-01 15:15 UTC, dsh2dsh commented on gamedata/config/text/rus/string_table_arhara.xml
> -		<text>��� �������� �����. � ���������, ������� ����������, � ��� ������� ������������ ��� ��� ����������. ����� ������ ���� ���� ������ ��������� ���������.</text>
Нет никакого смысла убирать отсюда эти строки.

2023-01-01 15:15 UTC, dsh2dsh commented on gamedata/config/text/rus/string_table_enc_equipment.xml
> +	<string id="arhara_obman1">
Тоже непонятные и бессмысленные изменения. Не нужно убирать эти строки.

2023-01-01 15:15 UTC, dsh2dsh commented on gamedata/config/text/rus/string_table_items.xml
>  	<string id="item_docs_hiden_pri_name">
И здесь тоже бессмысленные изменения.

2023-01-02 15:47 UTC, dsh2dsh requested changes

2023-01-02 15:47 UTC, dsh2dsh commented on gamedata/config/text/rus/string_table_enc_equipment.xml
> +	<string id="arhara_obman1">
Здесь все еще лишние изменения. Не нужно отсюда ничего убирать и переносить. Вообще не нужно ничего, никуда переносить в рамках текущей задачи.

2023-01-03 16:24 UTC, dsh2dsh requested changes

2023-01-03 16:24 UTC, dsh2dsh commented on gamedata/config/text/rus/string_table_enc_equipment.xml
> +
Вот эта строчка здесь не нужна. Все остальное нормально.

2023-01-03 20:21 UTC, dsh2dsh approved these changes

2023-01-03 20:22 UTC, merged